# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Dong-Geun Kim
title: Ph.D student
email: dgkim94@postech.ac.kr

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  dgkim94
instagram_username: dg_kim331
linkedin_username: dong-geun-kim-61609b315

# Additional icon links
additional_links:
- title: Lab. hompage
  icon: fas fa-globe
  url: interaction.postech.ac.kr

# About Section
about_profile_image: images/dgkim.jpg
about_content: |
  Hello, I'm Dong-Geun Kim, a Ph.D. student at POSTECH. My research interests include <mark>mid-air haptic rendering</mark>, <mark>haptic perception</mark>, and <mark>tactile language communication</mark>.

  I also enjoy <mark>watching baseball</mark> in my free time!

content:
  - title: Funded Projects
    layout: list
    content:
      - layout: left
        title: Multimodal Haptic Tool for AR Sports
        sub_title: Korea Creative Content Agency (KOCCA)
        caption: Jun. 2020 – Dec. 2022
        description: |
          Developed multimodal haptic feedback tools to enhance user experience in AR-based sports applications.

      - layout: left
        title: Performance Metric for User Experience
        sub_title: Google
        caption: Sep. 2021 – Jul. 2023
        description: |
          Designed performance metrics to assess and enhance user experience in interactive digital environments.

      - layout: left
        title: Mid-air Haptic Rendering for Digital Twin (PM)
        sub_title: Institute for Information & communications Technology Planning & Evaluation (IITP)
        caption: Jan. 2023 – Dec. 2024
        description: |
          Leading the development of real-time mid-air haptic rendering technologies integrated with digital twin systems.

      - layout: left
        title: Tactile Korean System for the Visually and Hearing Impaired
        sub_title: IITP
        caption: Jan. 2025 – Present
        description: |
          Conducting research on tactile delivery of Hangul using vibrotactile arrays to support communication for people with sensory disabilities.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Ulsan National Institute of Science and Technology (UNIST)
        caption: 2014 – 2019
        sub_title: B.S. in Mechanical Engineering

      - layout: left
        title: Pohang University of Science and Technology (POSTECH)
        caption: 2020 – Present
        sub_title: Integrated M.S./Ph.D. in IT Convergence Engineering

  - title: Publications
    layout: list
    content:
      - layout: left
        title: Tactile Enhancement of Mid-Air Ultrasonic Stimulation by Wrist Vibration: Perceived Intensity and Pattern Recognition
        sub_title: IEEE Transactions on Haptics (Under Review)
        description: |
          Investigated the effects of wrist-based tactile feedback on the perception and recognition of mid-air ultrasonic patterns.

      - layout: left
        title: A Feasibility Study on Tactile Enhancement of Mid-Air Ultrasonic Stimulation by Wrist Vibration
        sub_title: EuroHaptics 2024 Conference
        description: |
          Presented initial findings on tactile enhancement methods for mid-air ultrasonic feedback.

      - layout: left
        title: Encoding Korean Letters through Vibrotactile Patterns on the Forearm
        sub_title: In preparation
        description: |
          Designing a tactile communication system based on Korean Hangul using a 3x3 vibrotactile array.
