# Site
#repository: dgkim94/modern-resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Dong-Geun Kim
title: Ph.D student
email: dgkim94@postech.ac.kr
#website: interaction.postech.ac.kr

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  dgkim94
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: dg_kim331
linkedin_username: dong-geun-kim-61609b315
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Lab. hompage
  icon: fas fa-globe
  url: interaction.postech.ac.kr
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/dgkim.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, I'm Dong-Geun Kim, a Ph.D. student at POSTECH. My research interests include <mark>mid-air haptic rendering</mark>, <mark>haptic perception</mark>, and <mark>tactile language communication</mark>.

  I also enjoy <mark>playing baseball</mark> in my free time!

  <a href="/files/DongGeunKim_CV.pdf" target="_blank"><i class="fas fa-file-download"></i> Download CV</a>

content:
  - title: Funded Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Multimodal Haptic Tool for AR Sports
        sub_title: Korea Creative Content Agency (KOCCA)
        # link_text: Project Website
        #additional_links:
          #- title:  Multimodal Haptic Tool for AR Sports
          #  sub_title: Korea Creative Content Agency (KOCCA)
            #icon: fab fa-github
            #url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        caption: Jun. 2020 – Dec. 2022
        description: |
          Developed multimodal haptic feedback tools to enhance user experience in AR-based sports applications.
          I was responsible for designing devices that render realistic haptic sensations by combining <mark>vibration</mark>, <mark>shear force</mark>, and <mark>impact</mark> feedback.
        additional_links:
          - title: Project Overview
            icon: fas fa-link
            url: https://dl.acm.org/doi/abs/10.1145/3550082.3564177

      - layout: left
        title: Performance Metric for User Experience
        sub_title: Google
        caption: Sep. 2021 – Jul. 2023
        description: |
          Designed performance metrics to assess and enhance user experience in interactive digital environments.
          I conducted research on haptic generation to improve user experience through <mark>cross-modal matching</mark> of sound and touch.
        additional_links:
            - title: Project Overview
              icon: fas fa-link
              url: https://ieeexplore.ieee.org/abstract/document/10337769
      - layout: left
        title: Mid-air Haptic Rendering for Digital Twin  <mark>(PM)</mark>
        sub_title: Institute for Information & communications Technology Planning & Evaluation (IITP)
        caption: Jan. 2023 – Dec. 2024
        description: |
          Leading the development of real-time mid-air haptic rendering technologies integrated with digital twin systems.
          I conducted research on enhancing the perceived intensity of weak mid-air tactile stimuli using cognitive modulation techniques within a digital twin framework.
        additional_links:
           - title: Project Overview
             icon: fas fa-link
             url: https://link.springer.com/chapter/10.1007/978-3-031-70061-3_1

      - layout: left
        title: Tactile Korean System for the Visually and Hearing Impaired <mark>(PM)</mark>
        sub_title: Institute for Information & communications Technology Planning & Evaluation (IITP)
        caption: Jan. 2025 – Present
        description: |
          Conducting research on tactile delivery of korean language using vibrotactile arrays to support communication for people with sensory disabilities.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: POSTECH Kim Lab
        caption: Sep. 2019 – May 2020
        sub_title: Research Assistant
        description: |
          Developed high-frequency ultrasound transducers for tactile applications.
          Focused on hardware prototyping, acoustic modeling, and signal control to enable precise ultrasonic stimulation.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Ulsan National Institute of Science and Technology (UNIST)
        caption: 2014 – 2019
        sub_title: B.S. in Mechanical Engineering
        quote: >
          UNIST is one of Korea’s top science and technology universities, offering an interdisciplinary curriculum that combines fundamental engineering with innovation-driven research.
        description: |
          I studied mechanical engineering at UNIST, building a strong foundation in physical systems and dynamics. Based on the knowledge and problem-solving mindset I acquired there, I progressed into the IT Convergence program at POSTECH, where I now integrate mechanical and computational knowledge to conduct advanced haptic research.
      - layout: left
        title: Pohang University of Science and Technology (POSTECH)
        caption: 2020 – Present
        sub_title: Integrated M.S./Ph.D. in IT Convergence Engineering
        quote: >
          POSTECH is a world-class research-oriented university consistently ranked among the top in Asia, renowned for its cutting-edge research environment and strong emphasis on interdisciplinary innovation.
        description: |
          I am currently pursuing an integrated M.S./Ph.D. program in IT Convergence Engineering at POSTECH.
          By leveraging both mechanical and computational knowledge, I am actively conducting interdisciplinary research in the field of haptics, focusing on tactile perception, mid-air stimulation, and language-based tactile communication.
          This environment allows me to collaborate with experts across domains and develop impactful solutions in next-generation interaction technologies.

  - title: Publication
    layout: text
    content: | # this will include new lines to allow paragraphs
      <strong style="font-size: 1.1em;">[International Journal]</strong>

      [J1] <strong>Dong-Geun Kim</strong>, Seungmoon Choi, "Tactile Enhancement of Mid-Air Ultrasonic Stimulation by Wrist Vibration: Perceived Intensity and Pattern Recognition". IEEE Transactions on Haptics (Under Review)

      [J2] <strong>Dong-Geun Kim</strong>, Jungeun Lee, Gyeore Yun, Hong Z. Tan, and Seungmoon Choi, "Sound-to-Touch Crossmodal Pitch Matching for Short Sounds", IEEE Transactions on Haptics, 2024.

      <strong style="font-size: 1.1em;">[International Conference]</strong>

      [C1] <strong>Dong-Geun Kim</strong> and Seungmoon Choi, "A Feasibility Study of Tactile Enhancement of Mid-Air Ultrasonic Stimulation by Wrist Vibration", Proceedings of EuroHaptics, 2024.

      [C2] Gyeore Yun, Minjae Mun, Jungeun Lee, <strong>Dong-Geun Kim</strong>, Hong Z Tan, and Seungmoon Choi, "Generating Real-Time, Selective, and Multimodal Haptic Effects from Sound for Gaming Experience Enhancement", Proceedings of the ACM CHI Conference on Human Factors in Computing Systems (CHI), 2023.

      [C3] Chaeyong Park, Jeongwoo Kim, <strong>Dong-Geun Kim</strong>, Seungjae Oh, and Seungmoon Choi, "Vibration-Augmented Buttons: Information Transmission Capacity and Application to Interaction Design", Proceedings of the ACM CHI Conference on Human Factors in Computing Systems (CHI), 2022.

      <strong style="font-size: 1.1em;">[International Poster/Demo]</strong>

      [PDA1] Gyeore Yun, Jungeun Lee, <strong>Dong-Geun Kim</strong>, Minjae Mun, Hong Z. Tan, and Seungmoon Choi, Real-Time, Selective, and Multimodal Haptic Feedback from Gameplay Sound, IEEE World Haptics Conference, 2023.

      [PDA2] <strong>Dong-Geun Kim</strong>, Jungeun Lee, and Seungmoon Choi, "MMGrip: A Handheld Multimodal Haptic Device Combining Vibration, Impact, and Shear for Realistic Expression of Contact", Proceedings of SIGGRAPH Asia Posters, December 6-9, 2022.

      <strong style="font-size: 1.1em;">[Domestic Conference]</strong>

      [C1] <strong>Dong-Geun Kim</strong> and Seungmoon Choi, "A Feasibility Study of Tactile Enhancement of Mid-Air Ultrasonic Stimulation by Wrist Vibration", Proceedings of Korea Haptics Conference, 2024.


      <strong style="font-size: 1.1em;">[Domestic Poster/Demo]</strong>

      [PDA1] Jeongwoo Kim, Jungeun Lee, <strong>Dong-Geun Kim</strong>, Ki-Min Kwon, Beomyoung Chung, Junseong Park, Taeuk Kang, Sangji Moon, Wonseok Leee, Sung H. Han, and Seungmoon Choi, "Investigating the Luxuriousness of Haptic Warning on the Steering Wheel", Spring Conference, The Acoustical Society of Korea, 2024.

      <strong style="font-size: 1.1em;">[Award]</strong>

      <strong>Best ToH Short Paper Award (Finalist)</strong>

      2024 IEEE Haptics Symposium (April 10, 2024)

      <strong>Dong-Geun Kim</strong>, Jungeun Lee, Gyeore Yun, Hong Z. Tan, and Seungmoon Choi

      <strong>Best Paper Award</strong>

      KSC 2022, Korean Institute of Information Scientists and Engineers (December 22, 2022)

      <strong>Dong-Geun Kim</strong>, Jungeun Lee, and Seungmoon Choi


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
#remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
